name: "Firebase Functions Mapper"
description: "Creates a command that can be used to deploy Firebase functions from an optional map of file names to function names and/or group names to function names"
inputs:
  mapping-file:
    description: Location of the file containing the mapping of file and/or group names to function names
    required: false
  files:
    description: List of files containing functions to deploy
    required: false
  names:
    description: List of function names to deploy
    required: false
  groups:
    description: List of groups to deploy
    required: false
  force:
    description: Force function deployment
    required: false
    default: false
  debug:
    description: Show debug text 
    required: false
    default: false
outputs:
  deploy-command:
    description: The command to be fed to the Firebase function deployer
runs:
  using: "node20"
  main: "src/index.js"
